make: program database kaydet

program: program.c
	 gcc program.c -o program -lreadline

database: database.c 
	gcc database.c -o database 

kaydet: kaydet.c 
	gcc kaydet.c -o kaydet

clear: 
	rm -rf *o shell
